# Generated by Django 5.1.2 on 2024-12-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this course was enrolled.",
                        verbose_name="Enrollment Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        help_text="Select the enrollment status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Select the course.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
            ],
        ),
    ]
