# Generated by Django 5.1.2 on 2024-12-21 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now,
                help_text="Upload the course image.",
                upload_to="courses/images/",
                verbose_name="Course Image",
            ),
            preserve_default=False,
        ),
    ]
