# Generated by Django 5.1.2 on 2024-12-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Quiz Title",
                    ),
                ),
                (
                    "total_marks",
                    models.IntegerField(
                        help_text="Enter the total marks.", verbose_name="Total Marks"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Select the course.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="Enter the question text.",
                        verbose_name="Question Text",
                    ),
                ),
                (
                    "option_a",
                    models.CharField(
                        help_text="Enter option A.",
                        max_length=255,
                        verbose_name="Option A",
                    ),
                ),
                (
                    "option_b",
                    models.CharField(
                        help_text="Enter option B.",
                        max_length=255,
                        verbose_name="Option B",
                    ),
                ),
                (
                    "option_c",
                    models.CharField(
                        help_text="Enter option C.",
                        max_length=255,
                        verbose_name="Option C",
                    ),
                ),
                (
                    "option_d",
                    models.CharField(
                        help_text="Enter option D.",
                        max_length=255,
                        verbose_name="Option D",
                    ),
                ),
                (
                    "correct_option",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizzes.quiz",
                    ),
                ),
            ],
        ),
    ]
