# Generated by Django 5.1.2 on 2024-12-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_lessons",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Enter the number of lessons completed.",
                        null=True,
                        verbose_name="Completed Lessons",
                    ),
                ),
                (
                    "quiz_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Enter the quiz scores.",
                        null=True,
                        verbose_name="Quiz Scores",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Select the course.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
            ],
        ),
    ]
