# Generated by Django 5.1.2 on 2024-12-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_userprogress_completed_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='completed_lessons',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Completed Lessons'),
        ),
    ]
