services:
  web:
    build: .
    container_name: elearning_web
    command: gunicorn elearning.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: elearning_db
    environment:
      POSTGRES_DB: elearning_db
      POSTGRES_USER: elearning_user
      POSTGRES_PASSWORD: elearning_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
