services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    networks:
      - elearning_network
    env_file:
      - .env

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elearning_network

volumes:
  static_data:
  media_data:
  postgres_data:

networks:
  elearning_network:
    driver: bridge
